### ISSUE TITLE
Events table & endpoint

### ISSUE THREAD

**Issue by SandroRybarik** [DullLab/project#16]
## Todo
Endpoint for serving events created by users to __EventBoard__(#10) view.

- [x] setup mysql driver for nodejs + database connection example file
- [x] Migrate database (create table for events)
`id[bigint]  |  title[varchar]  |  description[varchar]  |  startAt[date] |  endAtdate|  place[varchar]  |  created_at[timestamp]`, in pure SQL 

- [x] Retrieve entries function
- [x] Router function providing JSON respone
```JSON
{
   "data":[
      {
         "title":"string",
         "description":"string",
         "place":"string",
         "startAt":"date",
         "endAt":"date"
      }
   ]
}
```
- [x] hook endpoint path to funcition in __app.js__
- [x] write tests for endpoint

## additional functionality
- [x] generate dummy data before serving server into database

**Comment by SandroRybarik** [comment]
#17 
resolved
