### ISSUE TITLE
Footer partial

### ISSUE THREAD

**Issue by SandroRybarik** [DullLab/project#7]
Create footer.pug which will be included in layout.pug

**Design will be shared in BC**.

### Todo
Footer must contain these
- [ ] name of **our organisation**
- [ ] link to this *repository*
- [ ] link to *about us* view
